### PR TITLE
Added details of Keda and VK example

### PR DESCRIPTION
**Pull request by vishal-biyani**

### CODE REVIEW

**Review by tomkerkhove — APPROVED** [review]
LGTM

**Comment by tomkerkhove** [comment]
Can you fix the DCO issues please? Here is [some guidance](https://github.com/kedacore/keda/blob/master/CONTRIBUTING.md#i-didnt-sign-my-commit-now-what)

**Comment by vishal-biyani** [comment]
Sorry about that, fixed now!

**Comment by tomkerkhove** [comment]
No problem at all!

**Pull request merged**
